### ISSUE TITLE
Typo Report

### ISSUE THREAD

**Issue by Diean233** [matloff/worthycsds#1]
There is a small typo in the joke in the grad school section.

> To answer, I tell them an old joke: A man is walking on a dock and passes a huge yacht. The asks the onwer how much the yacht costs. The owner answers, "If you have to ask, then you can't afford it." The point is that, ...

In the second sentence of this paragraph, the word _onwer_ should be spelled as _owner_

Also, thank you for this manual, I think it is brief and pretty helpful for CS students!

**Comment by matloff** [comment]
Thanks, fixed now. And thanks for the feedback.
